# Generated by Django 5.2.5 on 2025-12-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, help_text='Path to profile picture image', max_length=255, null=True),
        ),
    ]
